---
title: "Research"
format:
  html:
    page-layout: full
    css: styles.css
---

Check my [Google Scholar](https://scholar.google.com/citations?user=6Nf6zMsAAAAJ&hl=zh-CN) for the full list of publications.


## Publications

-   Xiqian Cai, **Zhengquan Cheng**, Yang Jiao (2025). Skewed Aspirations: the Impact of Economic Inequality on Adolescent's Cognitive and Non-cognitive Performance in *Journal of Economic Behavior & Organization*.[[Link]](https://doi.org/10.1016/j.jebo.2025.107179)

-   Xiqian Cai, **Zhengquan Cheng**, Dongxu Li (2024). Balancing against Geopolitical Risk: Household Investment Portfolios during the US-China Trade War in *Finance Research Letters*. [[Link]](https://doi.org/10.1016/j.frl.2024.105703)

-   **Zhengquan Cheng** (2020). Does Exercise Habit Lead to Higher Income in *South China Journal of Economics* (Chinese in 南方经济).[[Link]](https://link.cnki.net/doi/10.19592/j.cnki.scje.371089) 

-   Pengxin Xie, Hongyu Chen, **Zhengquan Cheng**, Wei Fan, Shumin Ge (2025). How Does Courts Respond to the Platform Regulation Policy in Protecting Gig Workers? Evidence from Court Decisions in China in *Asia Pacific Journal of Human Resources*.[[Link]](https://doi.org/10.1111/1744-7941.70014) 



## Working Papers

-   Xiqian Cai, **Zhengquan Cheng**, Dongxu Li. The Last Straw that Breaks the Marriage: Stock Market Declines and Divorce Litigation Approvals.
  
-   Xiqian Cai, Shuai Chen, **Zhengquan Cheng**. MeToo Movement, Women's Empowerment, and Judges' Gender Gap in Decisions.

-   Xiqian Cai, Shuai Chen, **Zhengquan Cheng**, Emily Nix. Gender-Based Violence and Judge Response.

-   Xiqian Cai, **Zhengquan Cheng**, Wenchao Xu. Numbers Don’t Lie, But Brain Might: How Left-digit Bias Skews Judicial Outcomes in Court.

-   Xiqian Cai, **Zhengquan Cheng**, Songfa Zhong. Time is Money: Socioeconomic Status Influences Monetary Substitution for Imprisonment.
 
-   Xiqian Cai, **Zhengquan Cheng**, Yi Lu, Sherry Wu. Globalization and Prosocial Preference.

-   **Zhengquan Cheng**, Xiqian Cai. From Connectivity to Security: Rural E-Commerce and Crime Reduction in China.

-   **Zhengquan Cheng**, Yuxin Liu, Xingjin Yu. Can Digital Financial Inclusion Reduce Informal Financial Risk: Evidence from Judicial Documents in China.

-   **Zhengquan Cheng**, Lingxian Liu. Global Evidence on Gender Gap in Trust in Science and the Role of Belief.

-   **Zhengquan Cheng**, Lingxian Liu. Social Media Adoption and Fundraising Performance in China's Nonprofit Sector.

-   **Zhengquan Cheng**. Breaking the Overtime Cycle: The Role of Female Leadership in Shaping Government Work Practices.